// !!! This is a file automatically generated by hipify!!!
// Copyright (c) 2009-2022, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.

#pragma once

//------------------------------------------------------------------------

#define HR_MAXVIEWPORT_LOG2 11 // ViewportSize / PixelSize.
#define HR_SUBPIXEL_LOG2 4     // PixelSize / SubpixelSize.

#define HR_MAXBINS_LOG2 4 // ViewportSize / BinSize.
#define HR_BIN_LOG2 4     // BinSize / TileSize.
#define HR_TILE_LOG2 3    // TileSize / PixelSize.

#define HR_COVER8X8_LUT_SIZE 768 // 64-bit entries.
#define HR_FLIPBIT_FLIP_Y 2
#define HR_FLIPBIT_FLIP_X 3
#define HR_FLIPBIT_SWAP_XY 4
#define HR_FLIPBIT_COMPL 5

#define HR_BIN_STREAMS_LOG2 4
#define HR_BIN_SEG_LOG2 9  // 32-bit entries.
#define HR_TILE_SEG_LOG2 5 // 32-bit entries.

#define HR_MAXSUBTRIS_LOG2 24   // Triangle structs. Dictated by CoarseRaster.
#define HR_COARSE_QUEUE_LOG2 10 // Triangles.

#define HR_SETUP_WARPS 2
#define HR_SETUP_OPT_BLOCKS 8
#define HR_BIN_WARPS 16
#define HR_COARSE_WARPS 16 // Must be a power of two.
#define HR_FINE_MAX_WARPS 20

#define HR_EMBED_IMAGE_PARAMS 32 // Number of per-image parameter structs embedded in kernel launch parameter block.

//------------------------------------------------------------------------

#define HR_MAXVIEWPORT_SIZE (1 << HR_MAXVIEWPORT_LOG2)
#define HR_SUBPIXEL_SIZE (1 << HR_SUBPIXEL_LOG2)
#define HR_SUBPIXEL_SQR (1 << (HR_SUBPIXEL_LOG2 * 2))

#define HR_MAXBINS_SIZE (1 << HR_MAXBINS_LOG2)
#define HR_MAXBINS_SQR (1 << (HR_MAXBINS_LOG2 * 2))
#define HR_BIN_SIZE (1 << HR_BIN_LOG2)
#define HR_BIN_SQR (1 << (HR_BIN_LOG2 * 2))

#define HR_MAXTILES_LOG2 (HR_MAXBINS_LOG2 + HR_BIN_LOG2)
#define HR_MAXTILES_SIZE (1 << HR_MAXTILES_LOG2)
#define HR_MAXTILES_SQR (1 << (HR_MAXTILES_LOG2 * 2))
#define HR_TILE_SIZE (1 << HR_TILE_LOG2)
#define HR_TILE_SQR (1 << (HR_TILE_LOG2 * 2))

#define HR_BIN_STREAMS_SIZE (1 << HR_BIN_STREAMS_LOG2)
#define HR_BIN_SEG_SIZE (1 << HR_BIN_SEG_LOG2)
#define HR_TILE_SEG_SIZE (1 << HR_TILE_SEG_LOG2)

#define HR_MAXSUBTRIS_SIZE (1 << HR_MAXSUBTRIS_LOG2)
#define HR_COARSE_QUEUE_SIZE (1 << HR_COARSE_QUEUE_LOG2)

//------------------------------------------------------------------------
// When evaluating interpolated Z pixel centers, we may introduce an error
// of (+-HR_LERP_ERROR) ULPs.

#define HR_LERP_ERROR(SAMPLES_LOG2) (2200u << (SAMPLES_LOG2))
#define HR_DEPTH_MIN HR_LERP_ERROR(3)
#define HR_DEPTH_MAX (HR_U32_MAX - HR_LERP_ERROR(3))

//------------------------------------------------------------------------
