// !!! This is a file automatically generated by hipify!!!
// Copyright (c) 2009-2022, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.

#include "Defs.hpp"
#include "../HipRaster.hpp"
#include "RasterImpl.hpp"

using namespace HR;

//------------------------------------------------------------------------
// Stub interface implementation.
//------------------------------------------------------------------------

HipRaster::HipRaster()
{
    m_impl = new RasterImpl();
}

HipRaster::~HipRaster()
{
    delete m_impl;
}

void HipRaster::setBufferSize(int width, int height, int numImages)
{
    m_impl->setBufferSize(Vec3i(width, height, numImages));
}

void HipRaster::setViewport(int width, int height, int offsetX, int offsetY)
{
    m_impl->setViewport(Vec2i(width, height), Vec2i(offsetX, offsetY));
}

void HipRaster::setRenderModeFlags(U32 flags)
{
    m_impl->setRenderModeFlags(flags);
}

void HipRaster::deferredClear(U32 clearColor)
{
    m_impl->deferredClear(clearColor);
}

void HipRaster::setVertexBuffer(void *vertices, int numVertices)
{
    m_impl->setVertexBuffer(vertices, numVertices);
}

void HipRaster::setIndexBuffer(void *indices, int numTriangles)
{
    m_impl->setIndexBuffer(indices, numTriangles);
}

bool HipRaster::drawTriangles(const int *ranges, bool peel, hipStream_t stream)
{
    return m_impl->drawTriangles((const Vec2i *)ranges, peel, stream);
}

void *HipRaster::getColorBuffer(void)
{
    return m_impl->getColorBuffer();
}

void *HipRaster::getDepthBuffer(void)
{
    return m_impl->getDepthBuffer();
}

void HipRaster::swapDepthAndPeel(void)
{
    m_impl->swapDepthAndPeel();
}

//------------------------------------------------------------------------
